name: Bug Report
description: バグレポートメモ
labels: [bug]
assignees:
  - mimikun
body:
  - type: markdown
    attributes:
      value: |
        過去に報告されたことのない、あるいはすでに修正されたことのない、新しいバグを提出していることを確認してください。

        issue のタイトルは、簡潔で明確なものを使用してください。
  - type: textarea
    attributes:
      label: 問題を再現するための手順
      description: 何をしようとしていたのか？
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: 期待される振る舞い
      description: どのように動いてほしかったですか？
    validations:
      required: true
  - type: input
    attributes:
      label: 実際の振る舞い
      description: 実際にはどのように動きましたか？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 詳細説明
    validations:
      required: false
  - type: textarea
    attributes:
      label: 環境
      description: |
        このバグを発見したMastodonのバージョンまたはコミットハッシュは何ですか？

        フロントエンドの問題の場合、使用していたブラウザとOSを教えてください。
      placeholder: |
        Mastodon 3.5.3 (or Edge)
        Ruby 2.7.6 (or v3.1.2)
        Node.js 16.18.0

        Google Chrome 106.0.5249.119
        Firefox 105.0.3

        など...
    validations:
      required: true
